# Generated by promptkit -- do not edit. Regenerate with: promptkit update

CARGO ?= cargo
PROFILE ?= release
TARGET_DIR ?= target

VERSION   = $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
GIT_COMMIT = $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")

all: build

# Build all binaries
.PHONY: build
build:
	$(CARGO) build --profile $(PROFILE) --bin syauth

# Show help
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  build            - Build all binaries (release)"
	@echo "  install          - Install binaries to ~/.cargo/bin"
	@echo "  test             - Run all tests"
	@echo "  testv            - Run all tests (verbose)"
	@echo "  lint             - Run clippy, fmt check, and audit"
	@echo "  fmt              - Format code"
	@echo "  audit            - Run cargo audit"
	@echo "  clean            - Clean build artifacts"
	@echo "  bench            - Run benchmarks"
	@echo "  docker-build     - Build Docker image"
	@echo "  docker-test      - Build and run tests in Docker"

# Install binaries
.PHONY: install
install:
	$(CARGO) install --path . --bin syauth

# Run all tests
.PHONY: test
test:
	$(CARGO) test --all-targets --all-features

# Run all tests with verbose output
.PHONY: testv
testv:
	$(CARGO) test --all-targets --all-features -- --nocapture

# Run benchmarks
.PHONY: bench
bench:
	$(CARGO) bench --all-features

# Lint: clippy + fmt check + audit
.PHONY: lint
lint:
	@echo "Running clippy..."
	$(CARGO) clippy --all-targets --all-features -- -D warnings
	@echo "Checking formatting..."
	$(CARGO) fmt --all --check
	@echo "Running cargo audit..."
	$(CARGO) audit || true
	@echo "Linting complete"

# Format code
.PHONY: fmt
fmt:
	$(CARGO) fmt --all

# Security audit
.PHONY: audit
audit:
	$(CARGO) audit

# Clean build artifacts
.PHONY: clean
clean:
	$(CARGO) clean

# =============================================================================
# Docker targets
# =============================================================================

DOCKER_IMAGE ?= syauth
DOCKER_TAG ?= latest

## docker-build: Build Docker image
.PHONY: docker-build
docker-build:
	@echo "Building Docker image $(DOCKER_IMAGE):$(DOCKER_TAG)..."
	docker build \
		--build-arg VERSION=$(VERSION) \
		--build-arg COMMIT=$(GIT_COMMIT) \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG) .
	@echo "Docker image built: $(DOCKER_IMAGE):$(DOCKER_TAG)"

## docker-test: Build Docker image and run tests
.PHONY: docker-test
docker-test: docker-build
	@echo "Running tests inside Docker container..."
	docker run --rm $(DOCKER_IMAGE):$(DOCKER_TAG) cargo test --all-targets
	@echo "Docker test passed"
