# Generated by promptkit -- do not edit. Regenerate with: promptkit update

CARGO ?= cargo
PROFILE ?= release
TARGET_DIR ?= target

VERSION   = $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
GIT_COMMIT = $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")

all: build

# Build the whole workspace (release). Produces:
#   - target/release/libpam_syauth.so (cdylib from crates/syauth-pam)
#   - target/release/syauth           (binary from crates/syauth-cli)
.PHONY: build
build:
	$(CARGO) build --profile $(PROFILE) --workspace

# Show help
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  build            - Build the whole workspace (release)"
	@echo "  install          - Install the syauth binary to ~/.cargo/bin"
	@echo "  test             - Run all tests (workspace)"
	@echo "  testv            - Run all tests (verbose)"
	@echo "  lint             - Run clippy, fmt check, audit, deny"
	@echo "  fmt              - Format code"
	@echo "  audit            - Run cargo audit (fatal)"
	@echo "  deny             - Run cargo deny check (fatal)"
	@echo "  clean            - Clean build artifacts"
	@echo "  bench            - Run benchmarks"
	@echo "  android-aar      - Build syauth_mobile.aar (requires NDK_HOME)"
	@echo "  android-aar-dry-run - Verify AAR pipeline without NDK"
	@echo "  android-test     - Run :app:connectedAndroidTest (skips cleanly without emulator/AAR)"
	@echo "  e2e-real         - Run the SPEC 4.3 nine-case suite against a real Android emulator (gated on SYAUTH_E2E_REAL=1)"
	@echo "  docker-build     - Build Docker image"
	@echo "  docker-test      - Build and run tests in Docker"

# Install the syauth CLI binary into ~/.cargo/bin.
.PHONY: install
install:
	$(CARGO) install --path crates/syauth-cli --bin syauth

# Run all tests across the whole workspace.
.PHONY: test
test:
	$(CARGO) test --workspace --all-targets --all-features

# Run all tests with verbose output.
.PHONY: testv
testv:
	$(CARGO) test --workspace --all-targets --all-features -- --nocapture

# Run benchmarks (no-op until a crate adds a `[[bench]]` target).
.PHONY: bench
bench:
	$(CARGO) bench --workspace --all-features

# Lint pipeline. Short-circuits on the first failing tool so the first error
# the developer sees is the first thing to fix.
#
# Order:
#   1. clippy  (denies warnings)
#   2. fmt --check
#   3. cargo audit  (non-fatal in lint; sibling `audit` target is fatal)
#   4. cargo deny check  (fatal)
.PHONY: lint
lint:
	@echo "Running clippy..."
	$(CARGO) clippy --workspace --all-targets --all-features -- -D warnings
	@echo "Checking formatting..."
	$(CARGO) fmt --all --check
	@echo "Running cargo audit..."
	$(CARGO) audit || true
	@echo "Running cargo deny check..."
	$(CARGO) deny check
	@echo "Linting complete"

# Format code.
.PHONY: fmt
fmt:
	$(CARGO) fmt --all

# Security audit (fatal). Use `make lint` for the non-fatal CI variant.
.PHONY: audit
audit:
	$(CARGO) audit

# Cargo-deny check (advisories, bans, licenses, sources). Fatal.
.PHONY: deny
deny:
	$(CARGO) deny check

# Clean build artifacts
.PHONY: clean
clean:
	$(CARGO) clean

# =============================================================================
# Android AAR target (S-014)
# =============================================================================
#
# Builds `crates/syauth-mobile/target/syauth_mobile.aar` containing the
# .so for each Android ABI plus the UniFFI-generated Kotlin bindings.
#
# Requires (full build):
#   - rustup targets for aarch64-linux-android and armv7-linux-androideabi
#   - cargo-ndk:        cargo install cargo-ndk
#   - uniffi-bindgen:   cargo install uniffi-bindgen --version 0.29
#   - NDK_HOME env var pointing at an installed Android NDK
#
# Use `make android-aar-dry-run` on hosts without the NDK to validate the
# pipeline is wired up correctly without producing the artifact.

.PHONY: android-aar
android-aar:
	@bash scripts/build_aar.sh

## android-aar-dry-run: Verify the AAR build pipeline without an NDK.
.PHONY: android-aar-dry-run
android-aar-dry-run:
	@DRY_RUN=1 bash scripts/build_aar.sh

# =============================================================================
# Android scaffold target (S-015)
# =============================================================================
#
# Runs the instrumented Compose test that asserts the OOB string rendered
# via the UniFFI -> JNA -> Rust pipeline. Skips cleanly on hosts without
# the artifacts or without an emulator so CI is honest.
#
# Three preflight checks before delegating to Gradle, each with a clean
# skip path (exit 0 with an actionable message):
#
#   1. AAR present?               -> scripts/check_android_aar.sh
#   2. Emulator connected?        -> adb devices | grep -E 'device$$'
#   3. No hand-written JNI?       -> grep -rn 'external fun' syauth-android/

ANDROID_DIR ?= syauth-android

.PHONY: android-test
android-test:
	@set -eu; \
	echo "==> S-015 android-test: preflight"; \
	if ! bash scripts/check_android_aar.sh; then \
		echo "==> android-test: AAR missing — skipping (exit 0)"; \
		exit 0; \
	fi; \
	echo "==> Asserting no hand-written JNI under $(ANDROID_DIR)/"; \
	if grep -rn 'external fun' $(ANDROID_DIR)/ >/dev/null 2>&1; then \
		echo "ERROR: hand-written JNI detected (DoD #4 violation):"; \
		grep -rn 'external fun' $(ANDROID_DIR)/; \
		exit 1; \
	fi; \
	if ! command -v adb >/dev/null 2>&1; then \
		echo "==> adb not on PATH — skipping (install Android SDK platform-tools)"; \
		exit 0; \
	fi; \
	if ! adb devices 2>/dev/null | awk 'NR>1 && $$2=="device"{found=1} END{exit found?0:1}'; then \
		echo "==> (no Android emulator connected — skipping)"; \
		exit 0; \
	fi; \
	echo "==> Running ./gradlew :app:connectedAndroidTest"; \
	( cd $(ANDROID_DIR) && ./gradlew :app:connectedAndroidTest ); \
	echo "==> Asserting debug APK is < 10 MB"; \
	apk_path="$(ANDROID_DIR)/app/build/outputs/apk/debug/app-debug.apk"; \
	if [ -f "$$apk_path" ]; then \
		size_k=$$(du -k "$$apk_path" | cut -f1); \
		if [ "$$size_k" -gt 10240 ]; then \
			echo "ERROR: debug APK exceeds 10 MB ($$size_k KB)"; exit 1; \
		else \
			echo "==> Debug APK size: $$size_k KB (< 10 MB budget)"; \
		fi; \
	else \
		echo "==> Debug APK not present yet ($$apk_path) — Gradle may have skipped assembleDebug"; \
	fi

# =============================================================================
# E2E real-radio target (S-019)
# =============================================================================
#
# SPEC §4.3 — the nine wire cases driven against a real Android emulator
# and a real BLE radio. Gated on SYAUTH_E2E_REAL=1; default `make test`
# skips it so a developer box without an emulator/BLE stack stays green.
#
# The target chains three steps:
#   1. scripts/e2e-emulator-up.sh   — boot AVD, install APK, script pair
#   2. cargo test -p syauth --test e2e_real
#   3. scripts/e2e-emulator-down.sh — kill emulator, remove .env.e2e
#
# Each per-test #[tokio::test] in tests/e2e_real.rs reads SYAUTH_E2E_REAL
# at startup and skips with a single line when it's unset — so even an
# accidental `cargo test -p syauth --test e2e_real` on a vanilla box is
# safe.

.PHONY: e2e-real
e2e-real:
ifeq ($(SYAUTH_E2E_REAL),1)
	@./scripts/e2e-emulator-up.sh
	@$(CARGO) test --package syauth --test e2e_real -- --nocapture --test-threads=1
	@./scripts/e2e-emulator-down.sh
else
	@echo "==> e2e-real skipped: set SYAUTH_E2E_REAL=1 to run"
endif

# =============================================================================
# Docker targets
# =============================================================================

DOCKER_IMAGE ?= syauth
DOCKER_TAG ?= latest

## docker-build: Build Docker image
.PHONY: docker-build
docker-build:
	@echo "Building Docker image $(DOCKER_IMAGE):$(DOCKER_TAG)..."
	docker build \
		--build-arg VERSION=$(VERSION) \
		--build-arg COMMIT=$(GIT_COMMIT) \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG) .
	@echo "Docker image built: $(DOCKER_IMAGE):$(DOCKER_TAG)"

## docker-test: Build Docker image and run tests
.PHONY: docker-test
docker-test: docker-build
	@echo "Running tests inside Docker container..."
	docker run --rm $(DOCKER_IMAGE):$(DOCKER_TAG) cargo test --all-targets
	@echo "Docker test passed"
