# Generated by promptkit -- do not edit. Regenerate with: promptkit update

CARGO ?= cargo
PROFILE ?= release
TARGET_DIR ?= target

VERSION   = $(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
GIT_COMMIT = $(shell git rev-parse --short HEAD 2>/dev/null || echo "none")

all: build

# Build the whole workspace (release). Produces:
#   - target/release/libpam_syauth.so (cdylib from crates/syauth-pam)
#   - target/release/syauth           (binary from crates/syauth-cli)
.PHONY: build
build:
	$(CARGO) build --profile $(PROFILE) --workspace

# Show help
.PHONY: help
help:
	@echo "Available targets:"
	@echo "  build            - Build the whole workspace (release)"
	@echo "  install          - Install the syauth binary to ~/.cargo/bin"
	@echo "  test             - Run all tests (workspace)"
	@echo "  testv            - Run all tests (verbose)"
	@echo "  lint             - Run clippy, fmt check, audit, deny"
	@echo "  fmt              - Format code"
	@echo "  audit            - Run cargo audit (fatal)"
	@echo "  deny             - Run cargo deny check (fatal)"
	@echo "  clean            - Clean build artifacts"
	@echo "  bench            - Run benchmarks"
	@echo "  docker-build     - Build Docker image"
	@echo "  docker-test      - Build and run tests in Docker"

# Install the syauth CLI binary into ~/.cargo/bin.
.PHONY: install
install:
	$(CARGO) install --path crates/syauth-cli --bin syauth

# Run all tests across the whole workspace.
.PHONY: test
test:
	$(CARGO) test --workspace --all-targets --all-features

# Run all tests with verbose output.
.PHONY: testv
testv:
	$(CARGO) test --workspace --all-targets --all-features -- --nocapture

# Run benchmarks (no-op until a crate adds a `[[bench]]` target).
.PHONY: bench
bench:
	$(CARGO) bench --workspace --all-features

# Lint pipeline. Short-circuits on the first failing tool so the first error
# the developer sees is the first thing to fix.
#
# Order:
#   1. clippy  (denies warnings)
#   2. fmt --check
#   3. cargo audit  (non-fatal in lint; sibling `audit` target is fatal)
#   4. cargo deny check  (fatal)
.PHONY: lint
lint:
	@echo "Running clippy..."
	$(CARGO) clippy --workspace --all-targets --all-features -- -D warnings
	@echo "Checking formatting..."
	$(CARGO) fmt --all --check
	@echo "Running cargo audit..."
	$(CARGO) audit || true
	@echo "Running cargo deny check..."
	$(CARGO) deny check
	@echo "Linting complete"

# Format code.
.PHONY: fmt
fmt:
	$(CARGO) fmt --all

# Security audit (fatal). Use `make lint` for the non-fatal CI variant.
.PHONY: audit
audit:
	$(CARGO) audit

# Cargo-deny check (advisories, bans, licenses, sources). Fatal.
.PHONY: deny
deny:
	$(CARGO) deny check

# Clean build artifacts
.PHONY: clean
clean:
	$(CARGO) clean

# =============================================================================
# Docker targets
# =============================================================================

DOCKER_IMAGE ?= syauth
DOCKER_TAG ?= latest

## docker-build: Build Docker image
.PHONY: docker-build
docker-build:
	@echo "Building Docker image $(DOCKER_IMAGE):$(DOCKER_TAG)..."
	docker build \
		--build-arg VERSION=$(VERSION) \
		--build-arg COMMIT=$(GIT_COMMIT) \
		-t $(DOCKER_IMAGE):$(DOCKER_TAG) .
	@echo "Docker image built: $(DOCKER_IMAGE):$(DOCKER_TAG)"

## docker-test: Build Docker image and run tests
.PHONY: docker-test
docker-test: docker-build
	@echo "Running tests inside Docker container..."
	docker run --rm $(DOCKER_IMAGE):$(DOCKER_TAG) cargo test --all-targets
	@echo "Docker test passed"
