// Roadmap item S-015 — hello-world Compose screen.
// Roadmap item S-016 — Navigation-Compose graph wiring the home screen
//                      (S-015 OobScreen) and the new pairing screen.
// Roadmap item S-017 — adds an `approve` destination + switches the
//                      host to FragmentActivity (required by
//                      androidx.biometric:biometric's BiometricPrompt,
//                      which binds to the fragment manager for its
//                      dialog lifecycle).
//
// The S-015 OobScreen + OOB_TEST_TAG / OOB_RENDER_PREFIX / helloBondKey()
// names stay; the S-015 HelloWorldTest still targets them. The home
// route renders the S-015 OobScreen plus a "Pair" button that routes
// to the pair route. The `approve` route is reached only when a real
// challenge arrives (S-018 ships the CompanionDeviceService that
// navigates here); for S-017 the route is exercised via androidTest
// only — the placeholder text below proves the entry exists.
//
// The Rust call goes through `uniffi.syauth_mobile.oobCodeForBond`, which
// is generated by `uniffi-bindgen` and copied into the build by
// `scripts/build_aar.sh`. NO hand-written JNI exists in this file or any
// other file under `syauth-android/`; DoD #4 (S-015) is enforced by a
// grep guard in `make android-test`.
package com.sy.syauth.android

import android.bluetooth.BluetoothAdapter
import android.bluetooth.BluetoothManager
import android.content.Context
import android.os.Bundle
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTag
import androidx.compose.ui.unit.dp
import androidx.fragment.app.FragmentActivity
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import com.sy.syauth.android.pair.PairingScreen
import com.sy.syauth.android.pair.PairingViewModel
import com.sy.syauth.android.pair.api.BondPersister
import com.sy.syauth.android.pair.api.LescResult
import com.sy.syauth.android.pair.api.PairBackend
import com.sy.syauth.android.pair.api.PeerHandle
import com.sy.syauth.android.pair.api.PickPeerResult
import com.sy.syauth.android.pair.impl.ReflectionBondRemover
import com.sy.syauth.android.pair.impl.UniffiOobCalculator
import uniffi.syauth_mobile.oobCodeForBond

/**
 * Test tag attached to the OOB Text composable so the instrumented test
 * can find it without depending on the exact rendered string (which is
 * data-dependent on the bond_key fixture and the OOB word table).
 */
const val OOB_TEST_TAG: String = "syauth.hello.oob"

/** Test tag attached to the "Pair" button on the home route (S-016). */
const val HOME_PAIR_BUTTON_TAG: String = "syauth.home.pair"

/**
 * Fixed bond_key fixture used by the hello-world screen. 32 bytes, the
 * length the UniFFI contract requires. The bytes are deterministic
 * (`it.toByte()` so byte 0 is 0x00, byte 1 is 0x01, ..., byte 31 is 0x1F)
 * so the rendered words are stable across runs and CI hosts — making the
 * "OOB: ..." assertion in HelloWorldTest reproducible.
 */
fun helloBondKey(): ByteArray = ByteArray(32) { it.toByte() }

/**
 * Prefix every OOB render carries. The instrumented test asserts the
 * prefix; the four emoji words follow after a single space. The prefix is
 * defined as a constant so the test and the screen can never drift.
 */
const val OOB_RENDER_PREFIX: String = "OOB: "

/**
 * NavHost route names. Pulled out as constants so a future test can
 * navigate by route without hard-coding strings.
 */
object NavRoutes {
    const val HOME: String = "home"
    const val PAIR: String = "pair"
    const val APPROVE: String = "approve"
}

/**
 * Host activity. Extends `FragmentActivity` (not the bare
 * `ComponentActivity` S-015 used) because S-017's
 * `AndroidBiometricPresenter` requires a `FragmentActivity` host —
 * the `androidx.biometric:biometric` library binds to the fragment
 * manager for its dialog lifecycle.
 *
 * S-015's HelloWorldTest still passes because `FragmentActivity`
 * extends `ComponentActivity`; the test rule constructs the same type
 * either way.
 */
class MainActivity : FragmentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background,
                ) {
                    SyauthApp(applicationContext = applicationContext)
                }
            }
        }
    }
}

@Composable
private fun SyauthApp(applicationContext: Context) {
    val navController = rememberNavController()
    NavHost(navController = navController, startDestination = NavRoutes.HOME) {
        composable(NavRoutes.HOME) {
            HomeRoute(
                onPairTapped = { navController.navigate(NavRoutes.PAIR) },
            )
        }
        composable(NavRoutes.PAIR) {
            // Construct the production dependency graph for the pairing
            // ViewModel. The factory is created once per route entry; on
            // back-navigation Compose disposes the entry and the ViewModel
            // is GCed. PairBackend is a no-op stub for S-016 because the
            // real BT stack wiring lands in S-018; the rest is real prod.
            val context = applicationContext
            val factory = remember(context) { PairingViewModelFactoryHolder.build(context) }
            val viewModel: PairingViewModel = viewModel(factory = factory)
            val state by viewModel.state.collectAsState()
            PairingScreen(
                state = state,
                onStartScan = viewModel::onStartScanTapped,
                onCancel = viewModel::onCancelTapped,
                onOobYes = viewModel::onOobYesTapped,
                onOobNo = viewModel::onOobNoTapped,
                onDone = {
                    navController.popBackStack(NavRoutes.HOME, inclusive = false)
                },
            )
        }
        composable(NavRoutes.APPROVE) {
            // The Approve destination is reachable only when a real
            // challenge arrives (S-018). For S-017 we render a small
            // placeholder so the route is exercised; the real
            // ApproveScreen is constructed by S-018 with a
            // ChallengeFrame-bearing ViewModel and tested directly via
            // the androidTest fixture in `approve/ApproveScreenTest.kt`.
            Text(text = "Approve destination (driven by S-018).")
        }
    }
}

@Composable
private fun HomeRoute(onPairTapped: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        OobScreen()
        Spacer(modifier = Modifier.height(24.dp))
        Button(
            onClick = onPairTapped,
            modifier = Modifier.semantics { testTag = HOME_PAIR_BUTTON_TAG },
        ) {
            Text(text = "Pair")
        }
    }
}

@Composable
internal fun OobScreen() {
    val rendered by produceState(initialValue = "${OOB_RENDER_PREFIX}...") {
        // `oobCodeForBond` is pure CPU (HKDF-SHA256 expand + four table
        // lookups). On ARMv8 it takes microseconds; we still defer to a
        // `produceState` coroutine instead of calling on first composition
        // so a binding regression that hangs the call doesn't block the
        // UI thread forever. Any thrown MobileException is captured into
        // the rendered string so the test surfaces the failure rather
        // than crashing the activity.
        value = try {
            val words = oobCodeForBond(helloBondKey())
            OOB_RENDER_PREFIX + words.joinToString(" ")
        } catch (t: Throwable) {
            "${OOB_RENDER_PREFIX}ERR ${t.message ?: t::class.java.simpleName}"
        }
    }

    Text(
        text = rendered,
        modifier = Modifier
            .padding(16.dp)
            .semantics { testTag = OOB_TEST_TAG },
    )
}

/**
 * Factory glue: builds the production dependency graph for
 * [PairingViewModel]. Kept simple — no DI container; this is the entire
 * production wiring in one place so a reviewer can audit the seams.
 */
private object PairingViewModelFactoryHolder {
    fun build(context: Context): androidx.lifecycle.ViewModelProvider.Factory =
        object : androidx.lifecycle.ViewModelProvider.Factory {
            @Suppress("UNCHECKED_CAST")
            override fun <T : androidx.lifecycle.ViewModel> create(
                modelClass: Class<T>,
            ): T {
                val adapter: BluetoothAdapter? = runCatching {
                    val manager = context.getSystemService(Context.BLUETOOTH_SERVICE)
                        as? BluetoothManager
                    manager?.adapter
                }.getOrNull()
                return PairingViewModel(
                    backend = StubPairBackend(),
                    oobCalculator = UniffiOobCalculator(),
                    bondPersister = InMemoryBondPersister(),
                    bondRemover = ReflectionBondRemover(adapter = adapter),
                ) as T
            }
        }
}

/**
 * Placeholder [PairBackend] for S-016 — the real Bluetooth-stack wiring
 * lands in S-018 (CompanionDeviceService). The stub keeps the screen
 * from crashing on launch but does not advance past `Scanning`.
 *
 * On a developer device, tapping "Pair with computer" reaches `Scanning`
 * and stays there until S-018 plugs in the real backend. This is the
 * intentional behavior — DoR for S-018 explicitly assumes a working
 * Compose surface, which this commit delivers.
 */
private class StubPairBackend : PairBackend {
    override fun startScan() = Unit
    override fun stopScan() = Unit
    override fun pickPeer(peer: PeerHandle): PickPeerResult =
        PickPeerResult.Failed("pairing backend not yet implemented (S-018)")
    override fun awaitLescResult(): LescResult =
        LescResult.Failed("pairing backend not yet implemented (S-018)")
}

/**
 * Placeholder [BondPersister] for S-016 — the real bond-keystore wiring
 * will be added once the UniFFI surface exposes a "save bond" function
 * (future work, not in any current roadmap item). For now the persister
 * accepts every call and stores nothing; the ViewModel-driven security
 * invariants ("persister NEVER called on Failed path") still hold
 * because the ViewModel is the only caller.
 */
private class InMemoryBondPersister : BondPersister {
    override fun persist(record: com.sy.syauth.android.pair.api.BondRecord) {
        // No-op: persistence is deferred to a future UniFFI-exposed store.
    }
}
