// Roadmap item S-015 — hello-world Compose screen.
// Roadmap item S-016 — Navigation-Compose graph wiring the home screen
//                      (S-015 OobScreen) and the new pairing screen.
// Roadmap item S-017 — adds an `approve` destination + switches the
//                      host to FragmentActivity (required by
//                      androidx.biometric:biometric's BiometricPrompt,
//                      which binds to the fragment manager for its
//                      dialog lifecycle).
//
// The S-015 OobScreen + OOB_TEST_TAG / OOB_RENDER_PREFIX / helloBondKey()
// names stay; the S-015 HelloWorldTest still targets them. The home
// route renders the S-015 OobScreen plus a "Pair" button that routes
// to the pair route. The `approve` route is reached only when a real
// challenge arrives (S-018 ships the CompanionDeviceService that
// navigates here); for S-017 the route is exercised via androidTest
// only — the placeholder text below proves the entry exists.
//
// The Rust call goes through `uniffi.syauth_mobile.oobCodeForBond`, which
// is generated by `uniffi-bindgen` and copied into the build by
// `scripts/build_aar.sh`. NO hand-written JNI exists in this file or any
// other file under `syauth-android/`; DoD #4 (S-015) is enforced by a
// grep guard in `make android-test`.
package com.sy.syauth.android

import android.bluetooth.BluetoothAdapter
import android.bluetooth.BluetoothManager
import android.content.Context
import android.content.Intent
import android.os.Build
import android.os.Bundle
import android.util.Base64
import android.widget.Toast
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.semantics.testTag
import androidx.compose.ui.unit.dp
import androidx.fragment.app.FragmentActivity
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navOptions
import com.sy.syauth.android.approve.AndroidBiometricPresenter
import com.sy.syauth.android.approve.AndroidKeystoreSigner
import com.sy.syauth.android.approve.ApproveScreen
import com.sy.syauth.android.approve.ApproveViewModel
import com.sy.syauth.android.approve.InMemorySigningKeyProvider
import com.sy.syauth.android.approve.UniffiWireSigner
import com.sy.syauth.android.bg.B64_FLAGS
import com.sy.syauth.android.bg.EXTRA_CHALLENGE_B64
import com.sy.syauth.android.bg.EXTRA_HOSTNAME
import com.sy.syauth.android.bg.EXTRA_PEER_ID
import com.sy.syauth.android.bg.GattResponseSender
import com.sy.syauth.android.bg.SyauthGattHostService
import com.sy.syauth.android.pair.PairingScreen
import com.sy.syauth.android.pair.PairingViewModel
import com.sy.syauth.android.pair.api.LescResult
import com.sy.syauth.android.pair.api.PairBackend
import com.sy.syauth.android.pair.api.PeerHandle
import com.sy.syauth.android.pair.api.PickPeerResult
import com.sy.syauth.android.pair.impl.ReflectionBondRemover
import com.sy.syauth.android.pair.impl.UniffiOobCalculator
import com.sy.syauth.android.provision.BOOTSTRAP_NO_BOND_TOAST
import com.sy.syauth.android.provision.BondRecord
import com.sy.syauth.android.provision.BondStore
import com.sy.syauth.android.provision.DiskBondPersister
import com.sy.syauth.android.provision.bootstrapBond
import uniffi.syauth_mobile.oobCodeForBond

/**
 * Test tag attached to the OOB Text composable so the instrumented test
 * can find it without depending on the exact rendered string (which is
 * data-dependent on the bond_key fixture and the OOB word table).
 */
const val OOB_TEST_TAG: String = "syauth.hello.oob"

/** Test tag attached to the "Pair" button on the home route (S-016). */
const val HOME_PAIR_BUTTON_TAG: String = "syauth.home.pair"

/**
 * Fixed bond_key fixture used by the hello-world screen. 32 bytes, the
 * length the UniFFI contract requires. The bytes are deterministic
 * (`it.toByte()` so byte 0 is 0x00, byte 1 is 0x01, ..., byte 31 is 0x1F)
 * so the rendered words are stable across runs and CI hosts — making the
 * "OOB: ..." assertion in HelloWorldTest reproducible.
 */
fun helloBondKey(): ByteArray = ByteArray(32) { it.toByte() }

/**
 * Prefix every OOB render carries. The instrumented test asserts the
 * prefix; the four emoji words follow after a single space. The prefix is
 * defined as a constant so the test and the screen can never drift.
 */
const val OOB_RENDER_PREFIX: String = "OOB: "

/**
 * NavHost route names. Pulled out as constants so a future test can
 * navigate by route without hard-coding strings.
 */
object NavRoutes {
    const val HOME: String = "home"
    const val PAIR: String = "pair"
    const val APPROVE: String = "approve"
}

/**
 * Host activity. Extends `FragmentActivity` (not the bare
 * `ComponentActivity` S-015 used) because S-017's
 * `AndroidBiometricPresenter` requires a `FragmentActivity` host —
 * the `androidx.biometric:biometric` library binds to the fragment
 * manager for its dialog lifecycle.
 *
 * S-015's HelloWorldTest still passes because `FragmentActivity`
 * extends `ComponentActivity`; the test rule constructs the same type
 * either way.
 */
/**
 * Payload extracted from an approve intent (S-018). Parsed once at
 * `onCreate` / `onNewIntent` and held in a `MutableState` so the
 * NavHost composable can react to a fresh approve request without
 * losing other state.
 */
internal data class ApprovePayload(
    val challengeBytes: ByteArray,
    val hostname: String,
    val peerId: String,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ApprovePayload) return false
        return challengeBytes.contentEquals(other.challengeBytes) &&
            hostname == other.hostname &&
            peerId == other.peerId
    }

    override fun hashCode(): Int {
        var result = challengeBytes.contentHashCode()
        result = 31 * result + hostname.hashCode()
        result = 31 * result + peerId.hashCode()
        return result
    }
}

internal fun parseApprovePayload(intent: Intent?): ApprovePayload? {
    if (intent == null) return null
    if (intent.action != Intent.ACTION_VIEW) return null
    val b64 = intent.getStringExtra(EXTRA_CHALLENGE_B64) ?: return null
    val hostname = intent.getStringExtra(EXTRA_HOSTNAME) ?: return null
    val peerId = intent.getStringExtra(EXTRA_PEER_ID) ?: return null
    val bytes = runCatching { Base64.decode(b64, B64_FLAGS) }.getOrNull() ?: return null
    return ApprovePayload(challengeBytes = bytes, hostname = hostname, peerId = peerId)
}

class MainActivity : FragmentActivity() {
    /**
     * Latest approve payload extracted from the activity's intent.
     * Mutated by both `onCreate` and `onNewIntent`; observed by the
     * Compose tree to navigate to the approve route.
     */
    internal val approvePayload = mutableStateOf<ApprovePayload?>(null)

    /**
     * Bond record resolved by the v0.1 demo bootstrap. The approve
     * route reads this to construct the Ed25519 signing key
     * provider (the seed lives in plaintext in app private storage;
     * the canonical Keystore-backed path is the v0.2 follow-up).
     *
     * Held in a `mutableStateOf` so Compose re-renders if a future
     * code path mutates the bond mid-session (none does today; the
     * field is read-once).
     */
    internal val bondRecord = mutableStateOf<BondRecord?>(null)

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        approvePayload.value = parseApprovePayload(intent)
        val record = runCatching { bootstrapBond(this) }.getOrNull()
        bondRecord.value = record
        if (record == null) {
            Toast.makeText(this, BOOTSTRAP_NO_BOND_TOAST, Toast.LENGTH_LONG).show()
        } else {
            runCatching {
                startForegroundService(Intent(this, SyauthGattHostService::class.java))
            }
        }
        setContent {
            MaterialTheme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background,
                ) {
                    SyauthApp(
                        activity = this,
                        approvePayload = approvePayload.value,
                        bondRecord = bondRecord.value,
                    )
                }
            }
        }
    }

    override fun onNewIntent(intent: Intent) {
        super.onNewIntent(intent)
        setIntent(intent)
        approvePayload.value = parseApprovePayload(intent)
    }
}

@Composable
private fun SyauthApp(
    activity: FragmentActivity,
    approvePayload: ApprovePayload?,
    bondRecord: BondRecord?,
) {
    val navController = rememberNavController()
    NavHost(navController = navController, startDestination = NavRoutes.HOME) {
        composable(NavRoutes.HOME) {
            HomeRoute(
                onPairTapped = { navController.navigate(NavRoutes.PAIR) },
            )
        }
        composable(NavRoutes.PAIR) {
            // Construct the production dependency graph for the pairing
            // ViewModel. The factory is created once per route entry; on
            // back-navigation Compose disposes the entry and the ViewModel
            // is GCed. PairBackend is a no-op stub for S-016 because the
            // real BT stack wiring lands in S-018; the rest is real prod.
            val context = activity.applicationContext
            val factory = remember(context) { PairingViewModelFactoryHolder.build(context) }
            val viewModel: PairingViewModel = viewModel(factory = factory)
            val state by viewModel.state.collectAsState()
            PairingScreen(
                state = state,
                onStartScan = viewModel::onStartScanTapped,
                onCancel = viewModel::onCancelTapped,
                onOobYes = viewModel::onOobYesTapped,
                onOobNo = viewModel::onOobNoTapped,
                onDone = {
                    navController.popBackStack(NavRoutes.HOME, inclusive = false)
                },
            )
        }
        composable(NavRoutes.APPROVE) {
            // Constructed when the user taps an approve notification.
            // The payload is captured at MainActivity-level; if it is
            // null we render a placeholder rather than crashing —
            // this branch is only reachable via direct navigation in
            // tests.
            if (approvePayload == null) {
                Text(text = "Approve destination (no payload).")
            } else {
                ApproveRoute(activity = activity, payload = approvePayload, bondRecord = bondRecord)
            }
        }
    }
    // Side-effect: when the activity receives a fresh approve payload
    // (cold-start or via onNewIntent), navigate to the approve route.
    NavigateOnApprovePayload(navController = navController, payload = approvePayload)
}

@Composable
private fun NavigateOnApprovePayload(
    navController: NavHostController,
    payload: ApprovePayload?,
) {
    if (payload == null) return
    androidx.compose.runtime.LaunchedEffect(payload) {
        val opts = navOptions {
            launchSingleTop = true
            popUpTo(NavRoutes.HOME) { inclusive = false }
        }
        navController.navigate(NavRoutes.APPROVE, opts)
    }
}

@Composable
private fun ApproveRoute(
    activity: FragmentActivity,
    payload: ApprovePayload,
    bondRecord: BondRecord?,
) {
    val seed = bondRecord?.phoneSigningKeySeed ?: ByteArray(ED25519_SEED_LEN)
    val viewModel = remember(payload, bondRecord) {
        ApproveViewModel(
            hostname = payload.hostname,
            challengeFrame = payload.challengeBytes,
            keystoreSigner = AndroidKeystoreSigner(),
            biometricPresenter = AndroidBiometricPresenter(
                activity = activity,
                hostname = payload.hostname,
            ),
            // v0.1 demo: the Ed25519 seed lives in plaintext under
            // app private storage and is loaded eagerly by the
            // bootstrap. The canonical Keystore-wrapped seed path
            // (documented under "Provision-file bootstrap (v0.1 demo)"
            // in docs/android-setup.md) replaces this in v0.2.
            signingKeyProvider = InMemorySigningKeyProvider(seed),
            wireSigner = UniffiWireSigner(),
            responseSender = GattResponseSender(peerId = payload.peerId),
        )
    }
    ApproveScreen(viewModel = viewModel)
}

/** Ed25519 seed length, named so we don't sprinkle the literal `32`. */
private const val ED25519_SEED_LEN: Int = 32

@Composable
private fun HomeRoute(onPairTapped: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        OobScreen()
        Spacer(modifier = Modifier.height(24.dp))
        Button(
            onClick = onPairTapped,
            modifier = Modifier.semantics { testTag = HOME_PAIR_BUTTON_TAG },
        ) {
            Text(text = "Pair")
        }
    }
}

@Composable
internal fun OobScreen() {
    val rendered by produceState(initialValue = "${OOB_RENDER_PREFIX}...") {
        // `oobCodeForBond` is pure CPU (HKDF-SHA256 expand + four table
        // lookups). On ARMv8 it takes microseconds; we still defer to a
        // `produceState` coroutine instead of calling on first composition
        // so a binding regression that hangs the call doesn't block the
        // UI thread forever. Any thrown MobileException is captured into
        // the rendered string so the test surfaces the failure rather
        // than crashing the activity.
        value = try {
            val words = oobCodeForBond(helloBondKey())
            OOB_RENDER_PREFIX + words.joinToString(" ")
        } catch (t: Throwable) {
            "${OOB_RENDER_PREFIX}ERR ${t.message ?: t::class.java.simpleName}"
        }
    }

    Text(
        text = rendered,
        modifier = Modifier
            .padding(16.dp)
            .semantics { testTag = OOB_TEST_TAG },
    )
}

/**
 * Factory glue: builds the production dependency graph for
 * [PairingViewModel]. Kept simple — no DI container; this is the entire
 * production wiring in one place so a reviewer can audit the seams.
 *
 * S-018 additions: injects a [com.sy.syauth.android.pair.impl.RealCompanionAssociator]
 * so the OOB-yes happy path also registers the bonded peer with
 * `CompanionDeviceManager.associate()`.
 */
private object PairingViewModelFactoryHolder {
    fun build(context: Context): androidx.lifecycle.ViewModelProvider.Factory =
        object : androidx.lifecycle.ViewModelProvider.Factory {
            @Suppress("UNCHECKED_CAST")
            override fun <T : androidx.lifecycle.ViewModel> create(
                modelClass: Class<T>,
            ): T {
                val adapter: BluetoothAdapter? = runCatching {
                    val manager = context.getSystemService(Context.BLUETOOTH_SERVICE)
                        as? BluetoothManager
                    manager?.adapter
                }.getOrNull()
                val associator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    com.sy.syauth.android.pair.impl.RealCompanionAssociator(context = context)
                } else {
                    // CompanionDeviceManager API requires API 26+.
                    // On older devices we fall through to the no-op
                    // associator — the ViewModel still completes the
                    // Yes path and emits `Bonded`, but the OS will
                    // not bind the service. This branch is unreachable
                    // because the app's minSdk is 26; the code exists
                    // so a future bump to a lower minSdk does not
                    // silently break.
                    com.sy.syauth.android.pair.NoopCompanionAssociator()
                }
                return PairingViewModel(
                    backend = StubPairBackend(),
                    oobCalculator = UniffiOobCalculator(),
                    bondPersister = DiskBondPersister(
                        bondStore = BondStore(context.filesDir),
                    ),
                    bondRemover = ReflectionBondRemover(adapter = adapter),
                    companionAssociator = associator,
                ) as T
            }
        }
}

/**
 * Placeholder [PairBackend] — the production BLE-scan/LESC-bond
 * wiring is out of scope for S-018 (which delivers the
 * CompanionDeviceService + GATT server background bridge instead).
 * The stub keeps the screen from crashing on launch but does not
 * advance past `Scanning`.
 *
 * Once a real backend is in place, the OOB-yes happy path will run
 * through the [com.sy.syauth.android.pair.impl.RealCompanionAssociator]
 * the S-018 factory now installs.
 */
private class StubPairBackend : PairBackend {
    override fun startScan() = Unit
    override fun stopScan() = Unit
    override fun pickPeer(peer: PeerHandle): PickPeerResult =
        PickPeerResult.Failed("pairing backend not yet implemented (post-S-018)")
    override fun awaitLescResult(): LescResult =
        LescResult.Failed("pairing backend not yet implemented (post-S-018)")
}

// The previous `InMemoryBondPersister` no-op was replaced by the
// disk-backed [com.sy.syauth.android.provision.DiskBondPersister].
// See `provision/DiskBondPersister.kt` for the v0.1 behaviour
// (writes a stub provision record into the BondStore so a future
// LESC backend has somewhere to land its full record).
