// Roadmap item S-018 — system-managed background bridge.
//
// `SyauthCompanionService` is the manifest-declared
// `CompanionDeviceService` subclass the OS binds whenever the
// bonded peer comes into BLE range. We never call
// `startForegroundService()` ourselves — the OS does, with the
// `connectedDevice` foreground sub-type declared in the manifest,
// so the binding survives doze for as long as the peer is observed.
//
// The service is a thin orchestrator:
//
//   1. `onDeviceAppeared` opens the GATT server (via
//      [GattServerController.start]).
//   2. The GATT server invokes the supplied `onChallenge` callback
//      whenever the desktop writes a valid frame to the challenge
//      characteristic.
//   3. The callback verifies the frame via UniFFI's
//      `verifyChallengeFrame(bondKey, frameBytes)`, looks up the
//      peer's friendly hostname, raises an approve notification,
//      and registers a [GattResponseSender] keyed by peerId so the
//      Approve flow can write the signed response back.
//   4. `onDeviceDisappeared` calls
//      [GattServerController.stop] and unregisters the response
//      sender for that peer.
//
// Every external dependency is injected via a `companion object`
// registry so the instrumented test
// (`androidTest/.../CdmLifecycleTest.kt`) can substitute a fake
// `GattServerController` without subclassing.
package com.sy.syauth.android.bg

import android.companion.AssociationInfo
import android.companion.CompanionDeviceService
import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import java.util.concurrent.ConcurrentHashMap

/**
 * Log tag used by every span the service emits. Pinned constant
 * because the field-inspection workflow (AGENTS.md /bt skill, Phase 5)
 * greps logcat by tag.
 */
internal const val SYAUTH_BG_LOG_TAG: String = "syauth.bg"

/**
 * Provider that builds a [GattServerController] for a freshly-bound
 * association. Production code installs a factory that opens a real
 * `BluetoothGattServer`; the instrumented test installs a factory
 * that returns a fake.
 */
public fun interface GattControllerFactory {
    public fun create(association: AssociationInfo): GattServerController
}

/**
 * Provider that resolves a bonded peer's hostname (for the
 * notification title). Tests inject a fixed mapping; production
 * wires a query against the bond store once that surface exists in
 * UniFFI (tracked as a follow-up; for S-018 the hostname falls
 * back to the association's `displayName`).
 */
public fun interface HostnameResolver {
    public fun hostnameFor(peerId: String): String
}

/**
 * Provider that resolves a peer's bond key (the BLAKE3 keyed-hash
 * key used by UniFFI's `verifyChallengeFrame`). Production wires
 * this to the bond store; tests inject a fixed map.
 *
 * Returns `null` when the peer is unknown — the service then drops
 * the frame silently.
 */
public fun interface BondKeyProvider {
    public fun bondKeyFor(peerId: String): ByteArray?
}

/**
 * Adapter so the service can call into the Rust UniFFI surface
 * without statically importing `uniffi.syauth_mobile` (which
 * blows up the JVM unit-test classpath with `UnsatisfiedLinkError`
 * unless the AAR is present).
 *
 * Production wires `UniffiChallengeVerifier` (below); tests inject
 * a fake.
 */
public fun interface ChallengeVerifier {
    /**
     * Verify [frameBytes] under [bondKey]. Returns the verified
     * challenge payload bytes on success, or `null` on any verify
     * failure / malformed frame.
     */
    public fun verify(bondKey: ByteArray, frameBytes: ByteArray): ByteArray?
}

/**
 * Production [ChallengeVerifier] backed by UniFFI's
 * `verifyChallengeFrame(bondKey, frameBytes)`. The Kotlin binding is
 * generated by `uniffi-bindgen` (see S-014) and copied into the AAR.
 *
 * Every error path is swallowed: `MobileException.VerifyFailed`,
 * `BadFrame`, and `InvalidKey` all map to `null`, which the service
 * interprets as "drop the frame silently". The desktop will time
 * out cleanly per SPEC §4.2.
 */
public class UniffiChallengeVerifier : ChallengeVerifier {
    override fun verify(bondKey: ByteArray, frameBytes: ByteArray): ByteArray? =
        try {
            uniffi.syauth_mobile.verifyChallengeFrame(bondKey, frameBytes)
        } catch (t: Throwable) {
            null
        }
}

@RequiresApi(Build.VERSION_CODES.S)
public class SyauthCompanionService : CompanionDeviceService() {

    /**
     * Per-association controller. Keyed by association id so
     * concurrent appear/disappear pairs for distinct peers don't
     * stomp on each other. Use a `ConcurrentHashMap` rather than a
     * single `AtomicReference` because the spec allows multiple
     * bonded peers in v0.2; for v0.1 only one slot is used at a
     * time but the data structure scales without refactor.
     */
    // Key type is `Int` (not `Long`): `AssociationInfo.getId()` on
    // Android API 31-36 returns a primitive `int`. The Kotlin type
    // mapping is `Int`, so the map key follows.
    private val controllers: ConcurrentHashMap<Int, GattServerController> =
        ConcurrentHashMap()

    override fun onDeviceAppeared(associationInfo: AssociationInfo) {
        super.onDeviceAppeared(associationInfo)
        val factory = gattControllerFactory
            ?: run {
                Log.w(LOG_TAG, "appeared peer=${associationInfo.id} but no factory installed")
                return
            }
        val controller = factory.create(associationInfo)
        controllers[associationInfo.id] = controller
        controller.start(associationInfo) { peerId, frameBytes ->
            handleChallenge(associationInfo, peerId, frameBytes)
        }
        Log.i(LOG_TAG, "appeared peer=${associationInfo.id} -> controller.start")
    }

    override fun onDeviceDisappeared(associationInfo: AssociationInfo) {
        super.onDeviceDisappeared(associationInfo)
        val controller = controllers.remove(associationInfo.id) ?: return
        controller.stop()
        Log.i(LOG_TAG, "disappeared peer=${associationInfo.id} -> controller.stop")
    }

    private fun handleChallenge(
        association: AssociationInfo,
        peerId: String,
        frameBytes: ByteArray,
    ) {
        val bondKey = bondKeyProvider?.bondKeyFor(peerId)
        if (bondKey == null) {
            Log.w(LOG_TAG, "frame from unknown peer=$peerId dropped")
            return
        }
        val verifier = challengeVerifier ?: return
        val payload = verifier.verify(bondKey, frameBytes)
        if (payload == null) {
            Log.w(LOG_TAG, "frame verify failed peer=$peerId; dropping")
            return
        }
        val hostname = hostnameResolver?.hostnameFor(peerId)
            ?: association.displayName?.toString()
            ?: peerId
        val id = ApproveNotification.show(this, payload, hostname, peerId)
        Log.i(LOG_TAG, "challenge accepted peer=$peerId nid=$id")
    }

    public companion object {
        internal const val LOG_TAG: String = SYAUTH_BG_LOG_TAG

        /**
         * Service-wide seam for GATT controller construction.
         * Installed by the app's `Application.onCreate` (or by the
         * instrumented test); read by the service on every
         * `onDeviceAppeared`. Volatile so cross-thread reads pick up
         * the latest install.
         */
        @Volatile
        public var gattControllerFactory: GattControllerFactory? = null

        /** Bond-key provider seam; see [BondKeyProvider]. */
        @Volatile
        public var bondKeyProvider: BondKeyProvider? = null

        /** Hostname resolver seam; see [HostnameResolver]. */
        @Volatile
        public var hostnameResolver: HostnameResolver? = null

        /** Challenge verifier seam; see [ChallengeVerifier]. */
        @Volatile
        public var challengeVerifier: ChallengeVerifier? = null

        /**
         * Reset all seams to `null`. Used by the instrumented test
         * to keep state clean between cases.
         */
        public fun resetSeams() {
            gattControllerFactory = null
            bondKeyProvider = null
            hostnameResolver = null
            challengeVerifier = null
        }
    }
}
