// Roadmap item S-017 — UniFFI WireSigner adapter.
//
// Production wiring for [WireSigner] that delegates to
// `uniffi.syauth_mobile.signChallengeResponse(seed, frame_bytes)`. The
// generated UniFFI binding throws a `MobileException.SignFailed` (or
// `InvalidKey` / `BadFrame`) on every error path; we translate them
// into a typed [WireSignResult.Failure] so the ViewModel does not have
// to catch anything.
//
// Imported separately from the rest of the approve package so the
// pure-JVM unit tests can avoid the JNA library load: the unit-test
// suite never references this file, only the [WireSigner] interface
// and the test fakes.
package com.sy.syauth.android.approve

/**
 * Production [WireSigner] backed by the UniFFI Kotlin binding.
 *
 * The class itself contains no JNI — the binding is auto-generated by
 * `uniffi-bindgen` and lives under
 * `crates/syauth-mobile/bindings/kotlin/uniffi/syauth_mobile/`. The
 * grep guard in `make android-test` asserts no hand-written `external
 * fun` exists in this file or any other under `syauth-android/`.
 */
public class UniffiWireSigner : WireSigner {
    override suspend fun signWire(bondKey: ByteArray, seed: ByteArray, frameBytes: ByteArray): WireSignResult {
        return try {
            // `buildResponseFrame` produces the full encoded response
            // frame the desktop's `Frame::decode` expects (version |
            // nonce | signature payload | MAC tag). Earlier S-017
            // returned `signChallengeResponse`'s raw 64-byte signature,
            // which the wire decoder rejected as `wrong-version`.
            val encoded = uniffi.syauth_mobile.buildResponseFrame(bondKey, seed, frameBytes)
            WireSignResult.Ok(encoded)
        } catch (t: Throwable) {
            WireSignResult.Failure(t.message ?: t::class.java.simpleName)
        }
    }
}
