// DEV-002: UniFFI [WireSigner] adapter that routes signing through
// the `FrameSigner` callback interface. The Ed25519 private key
// NEVER appears as bytes in the JVM — the Rust side calls back into
// a [com.sy.syauth.android.approve.KeystoreFrameSigner] (production)
// or a test fake (unit tests) which executes the sign operation under
// Android Keystore with `setUserAuthenticationRequired(true)` per
// SPEC §3.2 D6.
//
// The class itself contains no JNI — the binding is auto-generated by
// `uniffi-bindgen` and lives under
// `crates/syauth-mobile/bindings/kotlin/uniffi/syauth_mobile/`. The
// grep guard in `make android-test` asserts no hand-written `external
// fun` exists in this file or any other under `syauth-android/`.
package com.sy.syauth.android.approve

import uniffi.syauth_mobile.FrameSigner

/**
 * Production [WireSigner] backed by the UniFFI Kotlin binding.
 *
 * Wraps a [FrameSigner] — the production signer is a
 * [KeystoreFrameSigner] minted with the bond's Keystore alias; the
 * test wiring injects a fake that returns a canned signature without
 * touching the Keystore.
 */
public class UniffiWireSigner(private val frameSigner: FrameSigner) : WireSigner {
    override suspend fun signWire(bondKey: ByteArray, frameBytes: ByteArray): WireSignResult {
        return try {
            val encoded = uniffi.syauth_mobile.buildResponseFrame(bondKey, frameSigner, frameBytes)
            WireSignResult.Ok(encoded)
        } catch (t: Throwable) {
            WireSignResult.Failure(t.message ?: t::class.java.simpleName)
        }
    }
}
